name: Deploy AWS Lambda # Name of our job

on: 
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

jobs: 
  deploy-lambda:
    runs-on: ubuntu-latest # Specifies the runner
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python # Sets up python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies # Installs any packages
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS credentials # Sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda Function # Zips lambda directory and updates lambda function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
